name: Product Purchase flow Tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      # - uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: cypress-videos
      #     path: cypress/videos

      - name: Run k6 test
        uses: k6io/action@v0.1
        with:
          filename: LoadTest.html
      - name: Upload html report for job 1
        uses: actions/upload-artifact@v2
        with:
          #html file name define in k6 code
          name:   LoadTest
          # path in our github repo
          path:  LoadTest.html
          # available time period file after that is automatically remove from the workspace 
          retention-days: 2  
